### ISSUE TITLE
Sometimes flaky build with parallel build-option of Maven3

### ISSUE THREAD

**Issue by jbarop** [errai/errai#113]
When I build the Errai project with the parallel build-option of Maven 3 I get sometimes errors from a Errai generator:

```
jbarop@klootstock ~/c/errai (git:collapse-all-properties): mvn -T1C -o clean verify
....
[ERROR] java.util.concurrent.ExecutionException: java.lang.RuntimeException: could not load file
[ERROR]     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[ERROR]     at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[ERROR]     at org.jboss.errai.config.rebind.AsyncGenerators$FutureWrapper.get(AsyncGenerators.java:112)
[ERROR]     at org.jboss.errai.config.rebind.AsyncGenerators$FutureWrapper.get(AsyncGenerators.java:86)
[ERROR]     at org.jboss.errai.config.rebind.AbstractAsyncGenerator.startAsyncGeneratorsAndWaitFor(AbstractAsyncGenerator.java:188)
[ERROR]     at org.jboss.errai.marshalling.rebind.MarshallersGenerator.generate(MarshallersGenerator.java:226)
....
[ERROR] Caused by: java.io.FileNotFoundException: /Users/jbarop/code/errai/errai-navigation/target/classes/classlist.mf (No such file or directory)
[ERROR]     at java.io.FileInputStream.open(Native Method)
[ERROR]     at java.io.FileInputStream.<init>(FileInputStream.java:138)
[ERROR]     at org.jboss.errai.common.rebind.ClassListReader.getClassSetFromFile(ClassListReader.java:34)
```

The problem seems to appear when when more than one module is in the code generation phase. Seems to be threading fun :-)
I volunteer to investigate further if I have more time later in January.

**Comment by mbarkley** [comment]
We are disabling GitHub issues for this project in favour of issue tracking through [JIRA](https://issues.jboss.org/projects/ERRAI).

I believe this issue was fixed by ERRAI-1019 so there should be no further action required.
