### ISSUE TITLE
nullpointerexception

### ISSUE THREAD

**Issue by j-mi-jim** [errai/errai#150]
hi, getting the errai-tutorial-master (1.0.0-SNAPSHOT) and execute

mvn -D mobile cordova:build-project gives a nullpointerexception

[DEBUG]   Included: org.sonatype.gossip:gossip:jar:1.3
[DEBUG]   Included: com.thoughtworks.qdox:qdox:jar:1.12
[DEBUG]   Included: org.codehaus.groovy:groovy-all-minimal:jar:1.5.8
[DEBUG]   Included: org.apache.ant:ant:jar:1.8.2
[DEBUG]   Included: org.apache.ant:ant-launcher:jar:1.8.2
[DEBUG]   Included: jline:jline:jar:0.9.94
[DEBUG]   Included: junit:junit:jar:4.11
[DEBUG]   Included: org.hamcrest:hamcrest-core:jar:1.3
[DEBUG]   Included: org.apache.xbean:xbean-reflect:jar:3.4
[DEBUG]   Included: log4j:log4j:jar:1.2.17
[DEBUG]   Included: commons-logging:commons-logging-api:jar:1.1
[DEBUG]   Included: com.google.code.google-collections:google-collect:jar:snapshot-20080530
[DEBUG]   Included: org.codehaus.gmaven:gmaven-mojo-support:jar:1.5
[DEBUG]   Included: commons-configuration:commons-configuration:jar:1.6
[DEBUG]   Included: commons-collections:commons-collections:jar:3.2.1
[DEBUG]   Included: commons-lang:commons-lang:jar:2.6
[DEBUG]   Included: commons-logging:commons-logging:jar:1.1.1
[DEBUG]   Included: commons-digester:commons-digester:jar:1.8
[DEBUG]   Included: commons-beanutils:commons-beanutils:jar:1.7.0
[DEBUG]   Included: commons-beanutils:commons-beanutils-core:jar:1.8.0
[DEBUG]   Included: org.twdata.maven:mojo-executor:jar:2.2.0
[DEBUG]   Included: org.eclipse.aether:aether-util:jar:1.0.0.v20140518
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.2
[DEBUG]   Included: javax.el:javax.el-api:jar:3.0.0
[DEBUG]   Included: javax.interceptor:javax.interceptor-api:jar:1.2
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0.M1
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.3
[DEBUG]   Included: javax.inject:javax.inject:jar:1
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: com.google.guava:guava:jar:17.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.14
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.5.5
[DEBUG]   Included: org.sonatype.sisu:sisu-inject-bean:jar:2.2.3
[DEBUG]   Excluded: org.apache.maven:maven-project:jar:2.0.7
[DEBUG]   Excluded: org.apache.maven:maven-settings:jar:3.0
[DEBUG]   Excluded: org.apache.maven:maven-profile:jar:2.0.7
[DEBUG]   Excluded: org.apache.maven:maven-artifact-manager:jar:2.0.7
[DEBUG]   Excluded: org.apache.maven:maven-plugin-registry:jar:2.0.7
[DEBUG]   Excluded: org.codehaus.plexus:plexus-container-default:jar:1.0.0
[DEBUG]   Excluded: org.apache.maven:maven-core:jar:3.2.5
[DEBUG]   Excluded: org.apache.maven:maven-settings-builder:jar:3.2.5
[DEBUG]   Excluded: org.apache.maven:maven-repository-metadata:jar:3.0
[DEBUG]   Excluded: org.apache.maven:maven-model-builder:jar:3.2.5
[DEBUG]   Excluded: org.apache.maven:maven-aether-provider:jar:3.2.5
[DEBUG]   Excluded: org.eclipse.aether:aether-spi:jar:1.0.0.v20140518
[DEBUG]   Excluded: org.eclipse.aether:aether-impl:jar:1.0.0.v20140518
[DEBUG]   Excluded: org.eclipse.aether:aether-api:jar:1.0.0.v20140518
[DEBUG]   Excluded: org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0.M1
[DEBUG]   Excluded: org.codehaus.plexus:plexus-classworlds:jar:2.4
[DEBUG]   Excluded: org.apache.maven:maven-model:jar:3.0.5
[DEBUG]   Excluded: org.apache.maven:maven-plugin-api:jar:3.0.5
[DEBUG]   Excluded: org.apache.maven:maven-artifact:jar:3.0.5
[DEBUG]   Excluded: org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0
[DEBUG] Configuring mojo org.jboss.errai:cordova-maven-plugin:3.2.1.Final:build-project from plugin realm ClassRealm[plugin>org.jboss.errai:cordova-maven-plugin:3.2.1.Final, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'org.jboss.errai:cordova-maven-plugin:3.2.1.Final:build-project' with basic configurator -->
[DEBUG](f) project = MavenProject: org.jboss.errai.demo:errai-tutorial:1.0.0-SNAPSHOT @ C:\Users\jim\Downloads\errai-tutorial-master\pom.xml
[DEBUG](f) session = org.apache.maven.execution.MavenSession@cc62a3b
[DEBUG] -- end configuration --
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=268, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=51, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=1, ConflictResolver.conflictItemCount=126, DefaultDependencyCollector.collectTime=392, DefaultDependencyCollector.transformTime=2}
[DEBUG] org.apache.maven.plugins:maven-dependency-plugin:jar:2.1:
[DEBUG]    org.apache.maven:maven-artifact:jar:2.0.9:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.0.9:compile
[DEBUG]    org.apache.maven:maven-project:jar:2.0.9:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.0.9:compile
[DEBUG]       org.apache.maven:maven-profile:jar:2.0.9:compile
[DEBUG]       org.apache.maven:maven-artifact-manager:jar:2.0.9:compile
[DEBUG]       org.apache.maven:maven-plugin-registry:jar:2.0.9:compile
[DEBUG]    org.apache.maven:maven-model:jar:2.0.9:compile
[DEBUG]    org.apache.maven:maven-core:jar:2.0.9:compile
[DEBUG]       org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.9:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.0.9:compile
[DEBUG]       org.apache.maven:maven-error-diagnostics:jar:2.0.9:compile
[DEBUG]       commons-cli:commons-cli:jar:1.0:compile
[DEBUG]       org.apache.maven:maven-plugin-descriptor:jar:2.0.9:compile
[DEBUG]       org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile
[DEBUG]       org.apache.maven:maven-monitor:jar:2.0.9:compile
[DEBUG]       classworlds:classworlds:jar:1.1:compile
[DEBUG]    org.codehaus.plexus:plexus-archiver:jar:1.0-alpha-9:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:1.4.6:compile
[DEBUG]    org.apache.maven.shared:file-management:jar:1.1:compile
[DEBUG]       org.apache.maven.shared:maven-shared-io:jar:1.0:compile
[DEBUG]          org.apache.maven.wagon:wagon-provider-api:jar:1.0-alpha-6:compile
[DEBUG]    org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[DEBUG]       junit:junit:jar:3.8.1:compile
[DEBUG]    org.apache.maven.shared:maven-dependency-analyzer:jar:1.1:compile
[DEBUG]       asm:asm:jar:3.0:compile
[DEBUG]    org.apache.maven.shared:maven-dependency-tree:jar:1.2:compile
[DEBUG]    org.apache.maven.shared:maven-common-artifact-filters:jar:1.0:compile
[DEBUG]       org.apache.maven.shared:maven-plugin-testing-harness:jar:1.1:compile
[DEBUG]    org.codehaus.plexus:plexus-io:jar:1.0-alpha-1:compile
[DEBUG]    org.apache.maven.reporting:maven-reporting-api:jar:2.0.6:compile
[DEBUG]       org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7:compile
[DEBUG]    org.apache.maven.reporting:maven-reporting-impl:jar:2.0.4:compile
[DEBUG]       commons-validator:commons-validator:jar:1.2.0:compile
[DEBUG]          commons-beanutils:commons-beanutils:jar:1.7.0:compile
[DEBUG]          commons-digester:commons-digester:jar:1.6:compile
[DEBUG]             commons-collections:commons-collections:jar:2.1:compile
[DEBUG]          commons-logging:commons-logging:jar:1.0.4:compile
[DEBUG]          xml-apis:xml-apis:jar:1.0.b2:compile
[DEBUG]       org.apache.maven.doxia:doxia-core:jar:1.0-alpha-7:compile
[DEBUG]       oro:oro:jar:2.0.7:compile
[DEBUG]       org.apache.maven.doxia:doxia-site-renderer:jar:1.0-alpha-7:compile
[DEBUG]          org.codehaus.plexus:plexus-i18n:jar:1.0-beta-6:compile
[DEBUG]          org.codehaus.plexus:plexus-velocity:jar:1.1.2:compile
[DEBUG]             plexus:plexus-utils:jar:1.0.2:compile
[DEBUG]             commons-logging:commons-logging-api:jar:1.0.4:compile
[DEBUG]             velocity:velocity:jar:1.4:compile
[DEBUG]                velocity:velocity-dep:jar:1.4:runtime
[DEBUG]          org.apache.maven.doxia:doxia-decoration-model:jar:1.0-alpha-7:compile
[DEBUG] Created new class realm plugin>org.apache.maven.plugins:maven-dependency-plugin:2.1
[DEBUG] Importing foreign packages into class realm plugin>org.apache.maven.plugins:maven-dependency-plugin:2.1
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>org.apache.maven.plugins:maven-dependency-plugin:2.1
[DEBUG]   Included: org.apache.maven.plugins:maven-dependency-plugin:jar:2.1
[DEBUG]   Included: commons-cli:commons-cli:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4
[DEBUG]   Included: org.codehaus.plexus:plexus-archiver:jar:1.0-alpha-9
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.4.6
[DEBUG]   Included: org.apache.maven.shared:file-management:jar:1.1
[DEBUG]   Included: org.apache.maven.shared:maven-shared-io:jar:1.0
[DEBUG]   Included: junit:junit:jar:3.8.1
[DEBUG]   Included: org.apache.maven.shared:maven-dependency-analyzer:jar:1.1
[DEBUG]   Included: asm:asm:jar:3.0
[DEBUG]   Included: org.apache.maven.shared:maven-dependency-tree:jar:1.2
[DEBUG]   Included: org.apache.maven.shared:maven-common-artifact-filters:jar:1.0
[DEBUG]   Included: org.apache.maven.shared:maven-plugin-testing-harness:jar:1.1
[DEBUG]   Included: org.codehaus.plexus:plexus-io:jar:1.0-alpha-1
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:2.0.6
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-impl:jar:2.0.4
[DEBUG]   Included: commons-validator:commons-validator:jar:1.2.0
[DEBUG]   Included: commons-beanutils:commons-beanutils:jar:1.7.0
[DEBUG]   Included: commons-digester:commons-digester:jar:1.6
[DEBUG]   Included: commons-collections:commons-collections:jar:2.1
[DEBUG]   Included: commons-logging:commons-logging:jar:1.0.4
[DEBUG]   Included: xml-apis:xml-apis:jar:1.0.b2
[DEBUG]   Included: org.apache.maven.doxia:doxia-core:jar:1.0-alpha-7
[DEBUG]   Included: oro:oro:jar:2.0.7
[DEBUG]   Included: org.apache.maven.doxia:doxia-site-renderer:jar:1.0-alpha-7
[DEBUG]   Included: org.codehaus.plexus:plexus-i18n:jar:1.0-beta-6
[DEBUG]   Included: org.codehaus.plexus:plexus-velocity:jar:1.1.2
[DEBUG]   Included: plexus:plexus-utils:jar:1.0.2
[DEBUG]   Included: commons-logging:commons-logging-api:jar:1.0.4
[DEBUG]   Included: velocity:velocity:jar:1.4
[DEBUG]   Included: velocity:velocity-dep:jar:1.4
[DEBUG]   Included: org.apache.maven.doxia:doxia-decoration-model:jar:1.0-alpha-7
[DEBUG]   Excluded: org.apache.maven:maven-artifact:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-plugin-api:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-project:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-settings:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-profile:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-artifact-manager:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-plugin-registry:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-model:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-core:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-repository-metadata:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-error-diagnostics:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-plugin-descriptor:jar:2.0.9
[DEBUG]   Excluded: org.apache.maven:maven-monitor:jar:2.0.9
[DEBUG]   Excluded: classworlds:classworlds:jar:1.1
[DEBUG]   Excluded: org.apache.maven.wagon:wagon-provider-api:jar:1.0-alpha-6
[DEBUG]   Excluded: org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-dependency-plugin:2.1:unpack from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-dependency-plugin:2.1, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-dependency-plugin:2.1:unpack' with basic configurator -->
[DEBUG](s) groupId = org.jboss.errai
[DEBUG](s) artifactId = errai-cordova-template
[DEBUG](s) version = 3.2.1.Final
[DEBUG](s) type = tar.gz
[DEBUG](s) overWrite = false
[DEBUG](s) outputDirectory = C:\Users\jim\Downloads\errai-tutorial-master\target\template
[DEBUG](s) artifactItems = [org.jboss.errai:errai-cordova-template:3.2.1.Final:tar.gz]
[DEBUG](f) silent = false
[DEBUG](s) outputDirectory = C:\Users\jim\Downloads\errai-tutorial-master\target\dependency
[DEBUG](f) reactorProjects = [MavenProject: org.jboss.errai.demo:errai-tutorial:1.0.0-SNAPSHOT @ C:\Users\jim\Downloads\errai-tutorial-master\pom.xml]
[DEBUG](f) outputAbsoluteArtifactFilename = false
[DEBUG](f) project = MavenProject: org.jboss.errai.demo:errai-tutorial:1.0.0-SNAPSHOT @ C:\Users\jim\Downloads\errai-tutorial-master\pom.xml
[DEBUG](s) overWriteReleases = false
[DEBUG](s) markersDirectory = C:\Users\jim\Downloads\errai-tutorial-master\target\dependency-maven-plugin-markers
[DEBUG](s) overWriteIfNewer = true
[DEBUG](s) local =       id: local
      url: file:///C:/Users/jim/.m2/repository/
   layout: default
snapshots: [enabled => true, update => always]
 releases: [enabled => true, update => always]

[DEBUG](s) overWriteSnapshots = false
[DEBUG](s) remoteRepos = [      id: nexus
      url: http://192.168.20.81:8081/nexus/content/groups/InovelanGroup/
   layout: default
snapshots: [enabled => true, update => always]
 releases: [enabled => true, update => daily]
,       id: JBOSS_NEXUS
      url: http://repository.jboss.org/nexus/content/groups/public
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => true, update => daily]
,       id: central
      url: https://repo.maven.apache.org/maven2
   layout: default
snapshots: [enabled => false, update => daily]
 releases: [enabled => true, update => daily]
]
[DEBUG] -- end configuration --
[INFO] Configured Artifact: org.jboss.errai:errai-cordova-template:3.2.1.Final:tar.gz
[INFO] errai-cordova-template-3.2.1.Final.tar.gz already unpacked.
Copying 2235 files to C:\Users\jim\Downloads\errai-tutorial-master\target\template\platforms\android\assets\www
Copying 2235 files to C:\Users\jim\Downloads\errai-tutorial-master\target\template\platforms\ios\www
Copying 2235 files to C:\Users\jim\Downloads\errai-tutorial-master\target\template\www
Copying 1 file to C:\Users\jim\Downloads\errai-tutorial-master\src\main\webapp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.127 s
[INFO] Finished at: 2015-12-04T12:26:40+01:00
[INFO] Final Memory: 23M/260M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jboss.errai:cordova-maven-plugin:3.2.1.Final:build-project (default-cli) on project errai-tutorial: Execution default-cli of goal org.jboss.errai:cordova-maven-plugin:3.2.1.Final:build-project failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jboss.errai:cordova-maven-plugin:3.2.1.Final:build-project (default-cli) on project errai-tutorial: Execution default-cli of goal org.jboss.errai:cordova-maven-plugin:3.2.1.Final:build-project failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.jboss.errai:cordova-maven-plugin:3.2.1.Final:build-project failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at groovy.util.XmlSlurper.parse(XmlSlurper.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:86)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:230)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:912)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:756)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:738)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:726)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:170)
        at org.jboss.errai.maven.cordova.AndroidParser.updateAppNameInStrings(AndroidParser.groovy:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:86)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:230)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:912)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:78)
        at org.jboss.errai.maven.cordova.AndroidParser.updateProject(AndroidParser.groovy:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:86)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:230)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:912)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:756)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:750)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:730)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:170)
        at org.jboss.errai.maven.cordova.CordovaMojo.updateConfig(CordovaMojo.groovy:98)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:86)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:230)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:912)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:78)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrent0(ScriptBytecodeAdapter.java:112)
        at org.jboss.errai.maven.cordova.CordovaMojo.execute(CordovaMojo.groovy:44)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
C:\Users\jim\Downloads\errai-tutorial-master>

**Comment by mbarkley** [comment]
Hi @j-mi-jim 

Thanks for reporting this. It appears that there are missing files in the published `errai-cordova-template` for `3.2.1.Final`. As a workaround, I suggest switching your `cordova-maven-plugin` version to `3.2.0.Final`. There were no changes to `errai-cordova` between these versions.

Cheers.
