### ISSUE TITLE
TagCloudDemo not working with Jetty `mvn gwt:run -Pjetty`

### ISSUE THREAD

**Issue by BenDol** [errai/errai#202]
When running `mvn gwt:run -Pjetty` from the command line:
```
[INFO] --- gwt-maven-plugin:2.8.0:run (default-cli) @ errai-cdi-demo-tagcloud ---
[INFO] create exploded Jetty webapp in C:\Projects\errai\errai-demos\errai-cdi-demo-tagcloud\src\main\webapp
[INFO] auto discovered modules [org.jboss.errai.cdi.demo.tagcloud.TagCloudDemo]
[INFO] Super Dev Mode starting up
[INFO]    workDir: C:\Users\Ben\AppData\Local\Temp\gwt-codeserver-7611590966845255778.tmp
[INFO]    Loading inherited module 'org.jboss.errai.cdi.demo.tagcloud.TagCloudDemo'
[INFO]       Loading inherited module 'org.jboss.errai.bus.ErraiBus'
[INFO]          Loading inherited module 'org.jboss.errai.marshalling.ErraiMarshalling'
[INFO]             [ERROR] Unexpected error while processing XML
[INFO] java.lang.UnsupportedClassVersionError: org/jboss/errai/marshalling/rebind/MarshallersGenerator : Unsupported major.minor version 52.0
[INFO]  at java.lang.ClassLoader.defineClass1(Native Method)
[INFO]  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[INFO]  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[INFO]  at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[INFO]  at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[INFO]  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[INFO]  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[INFO]  at java.security.AccessController.doPrivileged(Native Method)
[INFO]  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[INFO]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[INFO]  at com.google.gwt.dev.cfg.ModuleDefSchema$ClassAttrCvt.convertToArg(ModuleDefSchema.java:899)
[INFO]  at com.google.gwt.dev.util.xml.HandlerArgs.convertToArg(HandlerArgs.java:64)
[INFO]  at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:221)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:296)
[INFO]  at org.apache.xerces.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:498)
[INFO]  at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:790)
[INFO]  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:827)
[INFO]  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1653)
[INFO]  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:324)
[INFO]  at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:875)
[INFO]  at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:798)
[INFO]  at org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:108)
[INFO]  at org.apache.xerces.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1198)
[INFO]  at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:564)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:349)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:70)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:431)
[INFO]  at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:316)
[INFO]  at com.google.gwt.dev.cfg.ModuleDefSchema$BodySchema.__inherits_begin(ModuleDefSchema.java:501)
[INFO]  at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:606)
[INFO]  at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:230)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:296)
[INFO]  at org.apache.xerces.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:498)
[INFO]  at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:180)
[INFO]  at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:811)
[INFO]  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:821)
[INFO]  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1653)
[INFO]  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:324)
[INFO]  at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:875)
[INFO]  at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:798)
[INFO]  at org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:108)
[INFO]  at org.apache.xerces.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1198)
[INFO]  at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:564)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:349)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:70)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:431)
[INFO]  at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:316)
[INFO]  at com.google.gwt.dev.cfg.ModuleDefSchema$BodySchema.__inherits_begin(ModuleDefSchema.java:501)
[INFO]  at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:606)
[INFO]  at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:230)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:296)
[INFO]  at org.apache.xerces.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:498)
[INFO]  at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:180)
[INFO]  at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:811)
[INFO]  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:821)
[INFO]  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1653)
[INFO]  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:324)
[INFO]  at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:875)
[INFO]  at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:798)
[INFO]  at org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:108)
[INFO]  at org.apache.xerces.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1198)
[INFO]  at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:564)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:349)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:70)
[INFO]  at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:431)
[INFO]  at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:316)
[INFO]  at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:243)
[INFO]  at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:193)
[INFO]  at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:151)
[INFO]  at com.google.gwt.dev.codeserver.Recompiler.loadModule(Recompiler.java:445)
[INFO]  at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:204)
[INFO]  at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:89)
[INFO]  at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
[INFO]  at com.google.gwt.dev.codeserver.CodeServer.makeOutboxTable(CodeServer.java:191)
[INFO]  at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:150)
[INFO]  at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:102)
[INFO]  at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:606)
[INFO]  at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
[INFO]  at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
[INFO]  at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:664)
[INFO]  at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:810)
[INFO]  at com.google.gwt.dev.DevMode.doStartup(DevMode.java:549)
[INFO]  at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:913)
[INFO]  at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
[INFO]  at com.google.gwt.dev.DevMode.main(DevMode.java:430)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

Or when running from Intellij Run Configuration:
```
"C:\Program Files\Java\jdk1.8.0_91\bin\java" "-Dmaven.home=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.6\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.6\plugins\maven\lib\maven3\bin\m2.conf" -Didea.launcher.port=7533 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.6\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.6\plugins\maven\lib\maven3\boot\plexus-classworlds-2.4.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 15.0.6\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=15.0.6 -DskipTests=true gwt:run -P !jetty
```

```
00:00:03.242 [WARN] Failed startup of context c.g.g.d.s.j.WebAppContextWithReload@3b9a8a75{/,file:/C:/Projects/errai/errai-demos/errai-cdi-demo-tagcloud/src/main/webapp/,STARTING}{C:\Projects\errai\errai-demos\errai-cdi-demo-tagcloud\src\main\webapp}
java.lang.IllegalArgumentException: Object of class 'com.google.gwt.dev.shell.jetty.JettyLauncher.WebAppContextWithReload' is not of type 'org.mortbay.jetty.webapp.WebAppContext'. Object Class and type Class are from different loaders. in file:/C:/Projects/errai/errai-demos/errai-cdi-demo-tagcloud/src/main/webapp/WEB-INF/jetty-env.xml 	
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:296) 	
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:248) 	
	at org.eclipse.jetty.plus.webapp.EnvConfiguration.configure(EnvConfiguration.java:124) 	
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:479) 	
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1337) 	
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) 	
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) 	
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:550) 	
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) 	
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) 	
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) 	
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) 	
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140) 	
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) 	
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) 	
	at org.eclipse.jetty.server.Server.start(Server.java:387) 	
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) 	
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) 	
	at org.eclipse.jetty.server.Server.doStart(Server.java:354) 	
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) 	
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:759) 	
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:634) 	
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923) 	
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706) 	
	at com.google.gwt.dev.DevMode.main(DevMode.java:430)
```

**Comment by BenDol** [comment]
If I change the first line in the `jetty-env.xml` file to this:
```xml
<Configure id="sample-weld" class="org.eclipse.jetty.webapp.WebAppContext">
```
It resolves the second error I get when running the project through the Intellij Run Config, but leaves me with more errors. Guessing this application hasn't been updated for GWT 2.8.0 yet.

```
Starting Jetty on port 8888
   [WARN] ServletContainerInitializers: detected. Class hierarchy: empty
[WARN] Server class 'javax.enterprise.inject.spi.BeanManager' could not be found in the web app, but was found on the system classpath
   [WARN] Adding classpath entry 'file:/C:/Users/Ben/.m2/repository/javax/enterprise/cdi-api/1.2/cdi-api-1.2.jar' to the web app classpath for this session
   [WARN] Failed startup of context c.g.g.d.s.j.WebAppContextWithReload@76fd1b9c{/,file:/C:/Users/Ben/.IntelliJIdea15/system/gwt/errai-cdi-demo-tagcloud.8a3eb67a/errai-cdi-demo-tagcloud.a9836a85/run/www/,STARTING}{C:\Users\Ben\.IntelliJIdea15\system\gwt\errai-cdi-demo-tagcloud.8a3eb67a\errai-cdi-demo-tagcloud.a9836a85\run\www}
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:408)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1340)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:550)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:759)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:634)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
	at com.google.gwt.dev.DevMode.main(DevMode.java:430)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.IllegalStateException: Nothing to bind for name BeanManager
	at org.eclipse.jetty.plus.webapp.PlusDescriptorProcessor.bindEntry(PlusDescriptorProcessor.java:895)
	at org.eclipse.jetty.plus.webapp.PlusDescriptorProcessor.bindResourceEnvRef(PlusDescriptorProcessor.java:822)
	at org.eclipse.jetty.plus.webapp.PlusDescriptorProcessor.visitResourceEnvRef(PlusDescriptorProcessor.java:367)
```

**Comment by mbarkley** [comment]
Hi @BenDol,

Yes, we have not kept up-to-date the few Jetty configurations remaining in our demos.

I have just updated the demo on our master branch to use the EmbeddedWildFlyLauncher for SDM like the rest of our demos. It now works with a simple `mvn clean gwt:run`.

Cheers.
